# Form implementation generated from reading ui file 'Window_2.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Window_2(object):
    def setupUi(self, Window_2):
        Window_2.setObjectName("Window_2")
        Window_2.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Window_2.setWindowIcon(icon)
        Window_2.setStyleSheet("background-color: rgb(245, 248, 250);\n"
"color: rgb(20, 23, 26);")
        Window_2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.backButton = QtWidgets.QPushButton(Window_2)
        self.backButton.setGeometry(QtCore.QRect(50, 520, 50, 50))
        self.backButton.setMinimumSize(QtCore.QSize(50, 50))
        self.backButton.setMaximumSize(QtCore.QSize(50, 50))
        self.backButton.setBaseSize(QtCore.QSize(50, 50))
        self.backButton.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.backButton.setStyleSheet("#backButton\n"
"{\n"
"color: #fff;\n"
"border-radius: 10%;\n"
"font-size: 24px;\n"
"font-weight: bold;\n"
"background-color: rgb(29, 161,242);\n"
"}\n"
"#backButton:hover\n"
"{\n"
"background-color: rgb(50, 119, 194);\n"
"}")
        self.backButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/arrow-left.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.backButton.setIcon(icon1)
        self.backButton.setIconSize(QtCore.QSize(28, 28))
        self.backButton.setObjectName("backButton")
        self.eye_detection = QtWidgets.QLabel(Window_2)
        self.eye_detection.setGeometry(QtCore.QRect(55, 65, 210, 330))
        self.eye_detection.setMaximumSize(QtCore.QSize(210, 330))
        self.eye_detection.setAutoFillBackground(False)
        self.eye_detection.setStyleSheet("#eye_detection\n"
"{\n"
"border-radius: 100%;\n"
"}")
        self.eye_detection.setText("")
        self.eye_detection.setPixmap(QtGui.QPixmap("Photos/eye_detection.jpg"))
        self.eye_detection.setScaledContents(False)
        self.eye_detection.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.eye_detection.setObjectName("eye_detection")
        self.color_detection = QtWidgets.QLabel(Window_2)
        self.color_detection.setGeometry(QtCore.QRect(295, 65, 210, 330))
        self.color_detection.setMaximumSize(QtCore.QSize(210, 330))
        self.color_detection.setAutoFillBackground(False)
        self.color_detection.setStyleSheet("")
        self.color_detection.setText("")
        self.color_detection.setPixmap(QtGui.QPixmap("Photos/color_detection.jpg"))
        self.color_detection.setScaledContents(False)
        self.color_detection.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.color_detection.setObjectName("color_detection")
        self.object_detection = QtWidgets.QLabel(Window_2)
        self.object_detection.setGeometry(QtCore.QRect(535, 65, 210, 330))
        self.object_detection.setMaximumSize(QtCore.QSize(210, 330))
        self.object_detection.setAutoFillBackground(False)
        self.object_detection.setStyleSheet("")
        self.object_detection.setText("")
        self.object_detection.setPixmap(QtGui.QPixmap("Photos/object_detection.jpg"))
        self.object_detection.setScaledContents(False)
        self.object_detection.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.object_detection.setObjectName("object_detection")
        self.eye_text = QtWidgets.QLabel(Window_2)
        self.eye_text.setGeometry(QtCore.QRect(55, 25, 210, 30))
        self.eye_text.setStyleSheet("#eye_text\n"
"{\n"
"font-family: \'Roboto\', sans-serif;\n"
"font-style: italic;\n"
"font-size: 24px;\n"
"}")
        self.eye_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.eye_text.setObjectName("eye_text")
        self.color_text = QtWidgets.QLabel(Window_2)
        self.color_text.setGeometry(QtCore.QRect(295, 25, 210, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(1)
        font.setItalic(True)
        self.color_text.setFont(font)
        self.color_text.setStyleSheet("#color_text\n"
"{\n"
"font-family: \'Roboto\', sans-serif;\n"
"font-style: italic;\n"
"font-size: 24px;\n"
"}")
        self.color_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.color_text.setObjectName("color_text")
        self.object_text = QtWidgets.QLabel(Window_2)
        self.object_text.setGeometry(QtCore.QRect(535, 25, 210, 24))
        self.object_text.setStyleSheet("#object_text\n"
"{\n"
"font-family: \'Roboto\', sans-serif;\n"
"font-style: italic;\n"
"font-size: 24px;\n"
"}")
        self.object_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.object_text.setObjectName("object_text")
        self.go_eye_Button = QtWidgets.QPushButton(Window_2)
        self.go_eye_Button.setGeometry(QtCore.QRect(96, 410, 128, 40))
        self.go_eye_Button.setStyleSheet("#go_eye_Button\n"
"{\n"
"color: #fff;\n"
"border-radius: 20%;\n"
"font-family: \'Roboto\', sans-serif;\n"
"font-style: italic;\n"
"font-size: 24px;\n"
"background-color: rgb(29, 161,242);\n"
"}\n"
"#go_eye_Button:hover\n"
"{\n"
"background-color: rgb(50, 119, 194);\n"
"}")
        self.go_eye_Button.setObjectName("go_eye_Button")
        self.go_color_Button = QtWidgets.QPushButton(Window_2)
        self.go_color_Button.setGeometry(QtCore.QRect(336, 410, 128, 40))
        self.go_color_Button.setStyleSheet("#go_color_Button\n"
"{\n"
"color: #fff;\n"
"border-radius: 20%;\n"
"font-family: \'Roboto\', sans-serif;\n"
"font-style: italic;\n"
"font-size: 24px;\n"
"background-color: rgb(29, 161,242);\n"
"}\n"
"#go_color_Button:hover\n"
"{\n"
"background-color: rgb(50, 119, 194);\n"
"}")
        self.go_color_Button.setObjectName("go_color_Button")
        self.go_object_Button = QtWidgets.QPushButton(Window_2)
        self.go_object_Button.setGeometry(QtCore.QRect(576, 410, 128, 40))
        self.go_object_Button.setStyleSheet("#go_object_Button\n"
"{\n"
"color: #fff;\n"
"border-radius: 20%;\n"
"font-family: \'Roboto\', sans-serif;\n"
"font-style: italic;\n"
"font-size: 24px;\n"
"background-color: rgb(29, 161,242);\n"
"}\n"
"#go_object_Button:hover\n"
"{\n"
"background-color: rgb(50, 119, 194);\n"
"}")
        self.go_object_Button.setObjectName("go_object_Button")

        self.retranslateUi(Window_2)
        QtCore.QMetaObject.connectSlotsByName(Window_2)

    def retranslateUi(self, Window_2):
        _translate = QtCore.QCoreApplication.translate
        Window_2.setWindowTitle(_translate("Window_2", "Computer Vision"))
        self.backButton.setToolTip(_translate("Window_2", "Go Back"))
        self.eye_text.setText(_translate("Window_2", "Eye Detection"))
        self.color_text.setText(_translate("Window_2", "Color Detection"))
        self.object_text.setText(_translate("Window_2", "Object Detection"))
        self.go_eye_Button.setText(_translate("Window_2", "GO"))
        self.go_color_Button.setText(_translate("Window_2", "GO"))
        self.go_object_Button.setText(_translate("Window_2", "GO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_2 = QtWidgets.QDialog()
    ui = Ui_Window_2()
    ui.setupUi(Window_2)
    Window_2.show()
    sys.exit(app.exec())
